### ISSUE TITLE
How does this repo relate to node-cs3apis?

### ISSUE THREAD

**Issue by michielbdejong** [cs3org/js-cs3apis#4]
Can someone explain the difference between https://github.com/cs3org/js-cs3apis and https://github.com/cs3org/node-cs3apis? Would be good to link these two repos from their readme's.

**Comment by michielbdejong** [comment]
Yes, I think the difference is that node-cs3apis includes a grpc client, and js-cs3apis does not. 

See https://github.com/cs3org/node-cs3apis/issues/6#issuecomment-940010392

But also see https://github.com/cs3org/node-cs3apis/issues/8
and https://github.com/cs3org/node-cs3apis/pull/10 about move from "just JavaScript support" to "JavaScript as well as TypeScript support".

Seeing also @marcolarosa 's experience in https://github.com/cs3org/reva/issues/2169
maybe we should just remove one of the two repos.

@labkode any preference of whether we keep 'js-cs3apis' or 'node-cs3apis'?
Now that people often generate client-side javascript from npm modules anyway, it probably no longer makes sense to have a separate 'node-' one, we can just have 'js-cs3apis' that includes the grpc client for node and the typings for TypeScript?

**Comment by marcolarosa** [comment]
@michielbdejong Out of curiosity, why is the grpc client include in the node repo and not in the js repo? Does that explain https://github.com/cs3org/js-cs3apis/issues/5?

**Comment by michielbdejong** [comment]
@marcolarosa I don't know the reasons, that was before my time. I'm now using [my add-typings branch](https://github.com/cs3org/ocm-test-suite/blob/main/package.json#L14) for
[the reva client in the ocm test suite](https://github.com/cs3org/ocm-test-suite/blob/main/clients/reva.ts), hth!

**Comment by michielbdejong** [comment]
Ah, actually I found https://github.com/grpc/grpc-web which seems related to how this repo works.
So it's probably worth keeping it around. But I'll improve the readme!
